### ISSUE TITLE
`mo-fmt` does not respect `.prettierrc`

### ISSUE THREAD

**Issue by ZenVoich** [dfinity/prettier-plugin-motoko#124]
`npx mo-fmt **/*.mo` - formats files ignoring options from `.prettierrc`

`npx prettier --write --plugin=prettier-plugin-motoko **/*.mo` - works well

my `.prettierrc`
```json
{
	"plugins": [
		"prettier-plugin-motoko"
	],
	"bracketSpacing": false,
	"printWidth": 220,
	"semi": true,
	"useTabs": true
}
```

**Comment by rvanasa** [comment]
Fixed in version 0.8.3. Cheers!
