### ISSUE TITLE
bug: using a quote in a comment breaks formatting

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/prettier-plugin-motoko#48]
# Issue

While adding following comment to one of my canister, I noticed that the auto formatting was breaking - was generating an incorrect format for my code.

```
/**
 * Does a bucket id exists? - i.e. not a bucket for a user but is a canister id linked to any user's bucket? 
 */
```

After debugging I noticed that the root cause was using a quote `'` in the comment. i.e. if I remove the quote, format is generated correctly.

**Comment by rvanasa** [comment]
Fixed in v0.1.6. Cheers!
