### ISSUE TITLE
comment blocks misformatted

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/prettier-plugin-motoko#64]
a comment block like this
<img width="383" alt="Screenshot 2022-10-19 at 09 01 16" src="https://user-images.githubusercontent.com/32162112/196619559-465b7f36-8923-4563-85c0-d9c62e2c55c4.png">
turns into this
<img width="945" alt="Screenshot 2022-10-19 at 09 02 00" src="https://user-images.githubusercontent.com/32162112/196619645-82ed6f07-fa56-4b44-a341-d8f30e98fd81.png">
and the compiler complains about an unclosed comment

**Comment by letmejustputthishere** [comment]
it would be cool if those comment blocks stay the same

**Comment by letmejustputthishere** [comment]
<img width="1221" alt="Screenshot 2022-10-21 at 14 15 22" src="https://user-images.githubusercontent.com/32162112/197193439-4c068e9c-83ae-4354-87c0-625b33b34941.png">
this behaviour seems to be weird as well

**Comment by letmejustputthishere** [comment]
^ actually doesn't seem to be restricted to comments
<img width="1741" alt="Screenshot 2022-10-21 at 15 58 30" src="https://user-images.githubusercontent.com/32162112/197213664-ab69bebc-a1a6-47e4-b1f1-d9c07a487205.png">

**Comment by rvanasa** [comment]
Strange! I'll look into this. Thank you for the examples.

**Comment by rvanasa** [comment]
Fixed the first example in version `0.2.3`. 

If you're still running into that alternating indentation issue, would you mind sending a copy/pasteable code snippet so I can fully recreate this on my end?

**Comment by letmejustputthishere** [comment]
I think it's easier if I just provide access to the repo, sent you an invite.
https://github.com/flowerpowerdao/punks-nft-canister/tree/ac9c898d81cb86f399bf98df57b6393e4425ec9d
